### ISSUE TITLE
Env Setup

### ISSUE THREAD

**Issue by TerraValidator** [figment-networks/hubble#33]
Hi, 

please help me to setup my server to use hubble

```
$ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

```
$cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```

I have this ERROR :

```
$git clone https://github.com/figment-networks/hubble
$cd hubble/bin
$./setup

== Installing dependencies ==
Successfully installed bundler-2.2.15
Parsing documentation for bundler-2.2.15
Done installing documentation for bundler after 4 seconds
1 gem installed
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

== Command ["bundle install"] failed ==
```

**Comment by pawelnguyen** [comment]
Hey @Masternode24, apologies for the late reply.

Did you manage to get it working? I haven't seen the error you mentioned before. Our readme for this repo is actually out of date, we're using Ruby 2.7.2 now and bundler 2.2.10

You don't need to run `./setup` anymore, here are most recent install steps. I'll update the readme later, **let me know if it helps**:

## Dependencies

- Ruby 2.6.6+ w/ Bundler 2+
- Node LTS
- Accessible PostgreSQL database
- Memcached running on localhost


## Usage

### Install

``` bash
bundle install
yarn
```

Install [libsecp256k1](https://github.com/bitcoin/secp256k1):

```bash
# ubuntu
sudo apt install libsecp256k1-dev
# mac
brew tap nervosnetwork/tap
brew install libsecp256k1

```

### Configuration

Generate encrypted secrets with `bin/rails secrets:setup`. Use config/encrypted_secrets_quickstart.yml to see what values are needed for what environments. Store config/secrets.yml.enc somewhere safe as it won't be committed.

Use an [environment manager](https://direnv.net/), or otherwise set these environment variables:

```bash
export HUBBLE_DATABASE_NAME=
export HUBBLE_DATABASE_HOST=
export HUBBLE_DATABASE_USER=
export HUBBLE_DATABASE_PASSWORD=
```

### Setup

```bash
bin/rake db:setup
```

This should create your database and output an admin setup link.

Start the server:

```
bin/rails s
```

Visit the admin setup link. In development, all 2fa is ignored. So type a password but ignore the 'confirm code' field. When logging into admin later, use `admin@figment.io` and again ignore the 2fa field.
